#!/bin/bash

if [ -z "$NAGIOS_PLUGIN_UTILS" ] ; then
    if [ -r /usr/lib64/nagios/plugins/utils.sh ] ; then
	NAGIOS_PLUGIN_UTILS=/usr/lib64/nagios/plugins/utils.sh
    elif [ -r /usr/lib/nagios/plugins/utils.sh ] ; then
	NAGIOS_PLUGIN_UTILS=/usr/lib/nagios/plugins/utils.sh
    fi
fi

if [ -z "$NAGIOS_PLUGIN_UTILS" -o ! -r $NAGIOS_PLUGIN_UTILS ] ; then
    echo Cannot find Nagios plugin utilities
    exit 2
fi

. $NAGIOS_PLUGIN_UTILS

NAGIOS_CMD=/var/nagios/rw/nagios.cmd
timeout=20
testname=jobsubmit
payload=eu.egi.sec

while test $# != 0 ; do
    case "$1" in
	-V|--version)
	    print_revision ARCCE-$testname 0.4
	    exit $STATE_OK
	    ;;
	-h|--help)
	    echo Valid options: -V, -h, -t, -w, -c, -H, -x, --vo, --payload
	    exit $STATE_OK
	    ;;
	-t|--timeout)
	    shift
	    timeout=$1
	    ;;
	-w|--warning)
	    shift
	    ;;
	-c|--critical)
	    shift
	    ;;
	-H|--hostname)
	    shift
	    hostname=$1
	    ;;
	-x|--proxy)
	    shift
	    export X509_USER_PROXY=$1
	    ;;
	--vo)
	    shift
	    VO=$1
	    ;;
	--payload)
	    shift
	    payload=$1
	    ;;
	*)
	    echo Unknown option "$1"
	    exit $STATE_UNKNOWN
	    ;;
    esac
    shift
done

if [ -z "$hostname" ] ; then
    echo "Missing hostname"
    exit $STATE_UNKNOWN
fi

confdir=/usr/libexec/grid-monitoring/probes/eu.egi.sec/ARC/$testname

jobdir=/var/lib/gridprobes/$VO/eu.egi.sec/ARCCE/$hostname/$testname
mkdir -p $jobdir

if [ -r $jobdir/jobid ] ; then
    arcstat -l -i $jobdir/jobid -t $timeout > $jobdir/status 2>&1
    jobstatus=`grep "^ Specific state:" $jobdir/status | sed -e "s/ Specific state:\s*//"`
    joberror=`grep "^ Job Error:" $jobdir/status | sed -e "s/ Job Error:\s*//"`
    jobwarn=`grep "^WARNING" $jobdir/status`
    #Get rid of stale jobs
    jobstale=`grep '^Warning: Job not found in job list' $jobdir/status`
    if [ -n "$jobstale" ] ; then
         rm -f $jobdir/jobid $jobdir/status
         msg='Found stale jobid. Removing it...\n'
    else
        case "$jobstatus" in
            "")
                  msg='Job state not available\n'"$jobwarn"
                  res=$STATE_WARNING
                  ;;
              "DELETED")
                  arcclean -i $jobdir/jobid -t $timeout > /dev/null 2>&1
                  echo 'Job: '`cat $jobdir/jobid`' deleted from LRMS'
                  rm -f $jobdir/jobid $jobdir/status
                  exit $STATE_WARNING
                  ;;
              "FAILED")
                  rm -rf $jobdir/$testname
                  rm -f $jobdir/jobid $jobdir/status
                  echo $joberror
                  exit $STATE_CRITICAL
                  ;;
              "FINISHED")
                  rm -rf $jobdir/$testname
                  arcget -i $jobdir/jobid -t $timeout -dir $jobdir -J > /dev/null 2>&1
    
                  for test in `cat $confdir/test_list`; do
                      if [ -s $jobdir/$testname/$test.res ] && [ -s $jobdir/$testname/$test.msg ] ; then
               	          tres=`cat $jobdir/$testname/$test.res`
                	  tmsg=`cat $jobdir/$testname/$test.msg|sed -e "1s/$/|/g"|sed ':a;N;$!ba;s/\n/\\\n/g'`
                	  time=`date +%s`
                	  echo "[$time] PROCESS_SERVICE_CHECK_RESULT;$hostname;eu.egi.sec.WN-$test-$VO;$tres;$tmsg" > $NAGIOS_CMD
                      else
                          time=`date +%s`
                          echo "[$time] PROCESS_SERVICE_CHECK_RESULT;$hostname;eu.egi.sec.WN-$test-$VO;3;(No output returned from plugin)" > $NAGIOS_CMD
                      fi
                  done
    
                  echo 'Job: '`cat $jobdir/jobid`'\nStatus: '$jobstatus' Results have been retrieved'
                  rm -f $jobdir/jobid $jobdir/status
                  exit $STATE_OK
                  ;;
               *)
                  msg="Job not finsihed yet: $jobstatus"
                  res=$STATE_OK
                  ;;
        esac
    fi

    if [ -r $jobdir/jobid ] ; then
        age=$(( `date +%s` - `stat -c %Y $jobdir/jobid` ))
           if [ $age -gt 21200 ] ; then # 6 hours
               arckill -i $jobdir/jobid -t $timeout > /dev/null 2>&1
               arcclean -i $jobdir/jobid -t $timeout > /dev/null 2>&1
               expjob=1
               msg+='\nJob: '`cat $jobdir/jobid`'\n not completed within 6 hours\n'
               rm -f $jobdir/jobid $jobdir/status
           fi
    fi
fi

if [ ! -r $jobdir/jobid ] ; then
    echo $NAGIOS__HOSTSITE_NAME > $jobdir/sitename
    cat $confdir/xrsl | sed -e "s#sitename_loc#$jobdir/sitename#g" > $jobdir/xrsl
    arcsub -c $hostname -o $jobdir/jobid -t $timeout $jobdir/xrsl > $jobdir/log 2>&1
    joblog=`grep "^ERROR" $jobdir/log`
    joblogfull=`cat $jobdir/log`
    msg+='Submitting job: '`cat $jobdir/jobid`'\n'
    res=$STATE_OK
    if [ -n "$expjob" ] && [ -r $jobdir/jobid ] ; then
        res=$STATE_WARNING
    fi
    if [ ! -s $jobdir/jobid ] ; then
        msg='There was an error submitting the job\n-----\nJob log:\n\n'"$joblogfull"
        rm -f $jobdir/jobid
	res=$STATE_CRITICAL
    else
	msg+='Job submission successful'
    fi
fi

echo "$msg"
exit $res

