#!/bin/bash

NAGIOS_OK=0
NAGIOS_ERROR=2

SINGULARITY_CONFIG=/etc/singularity/singularity.conf

SUID_SET="no"
for bin in /usr/libexec/singularity/bin/*-suid; do
    if [ -u "$bin" ]; then
        SUID_SET="yes"
        break
    fi
done
if [ "$SUID_SET" = "no" ]; then
    echo "no singularity suid command has the set-uid bit set"
    exit $NAGIOS_OK
fi

egrep -q '^\S*enable overlay = no' $SINGULARITY_CONFIG 2>/dev/null
if [ $? -eq 0 ]; then
    echo "Overlay is disabled by singularity"
    exit $NAGIOS_OK
fi

egrep -q '^\S*allow setuid = no' $SINGULARITY_CONFIG 2>/dev/null
if [ $? -eq 0 ]; then
    echo "Using of set-uid isn't enabled by singularity"
    exit $NAGIOS_OK
fi

echo "No known mitigation of EGI-SVG-2018-14213 detected"
exit $NAGIOS_ERROR
