#!/bin/bash

# nagios check for cvmfs local root exploit

PROBE_VERSION="v0.4"

NAGIOS_OK=0
NAGIOS_WARNING=1
NAGIOS_ERROR=2
NAGIOS_UNKNOWN=3

command -v cvmfs2 &>/dev/null
if [ $? -ne 0 ]; then
   MSG="no cvmfs package found"
   echo "OK: $MSG"
   exit $NAGIOS_OK
else
 VERSION=`echo "$(cvmfs2 -V 2>&1)" | sed -nre 's/[^0-9]*(([0-9]+\.)*[0-9]+).*/\1/p'`
 BRANCH=`echo "$(cvmfs2 -V 2>&1)" | sed -nre 's/[^0-9]+(([0-9]+\.){1}[0-9]+).*/\1/p'`
 BUILD=`echo $VERSION | sed -nre 's/([0-9]+\.)*//p'`

if [ $BRANCH == 2.0 ]; then
  if (( "$BUILD" >= "22" )); then
    MSG="Package version >= 2.0.22"
  elif (echo "639fa7fc467b67514671769dd1641d98  /etc/auto.cvmfs" | md5sum --check --status); then
    MSG="found /etc/auto.cvmfs from cvmfs-2.0.22-1"
  fi
fi  

if [ $BRANCH == 2.1 ]; then
  if (( "$BUILD" >= "14" )); then
    MSG="Package version >= 2.1.14"
  elif (echo "28f1694bb45236c5a70505d19b0f5135  /etc/auto.cvmfs" | md5sum --check --status); then
    MSG="found /etc/auto.cvmfs from cvmfs-2.1.14-1"
  fi
fi

MD5SUM=$(md5sum /etc/auto.cvmfs)

if [ -z "$MSG" ]; then
  echo "CRITICAL: ${VERSION}  package found without hotfix"
  echo "MD5 hash found $(md5sum /etc/auto.cvmfs)"
  echo "probe version ${PROBE_VERSION}"
  exit $NAGIOS_ERROR
else
  echo "OK: $MSG [${PROBE_VERSION}]"
  exit $NAGIOS_OK
fi
fi   

