#!/bin/bash

# nagios check for cvmfs local root exploit

PROBE_VERSION="v1.0"

NAGIOS_OK=0
NAGIOS_WARNING=1
NAGIOS_ERROR=2
NAGIOS_UNKNOWN=3

HASH2_0="639fa7fc467b67514671769dd1641d98"
HASH2_1="28f1694bb45236c5a70505d19b0f5134"

if !(command -v cvmfs2 &>/dev/null); then
   MSG="no cvmfs found"
   RC=$NAGIOS_OK
else
  CVMFS2V=$(cvmfs2 -V 2>&1)
  VERSION=${CVMFS2V##* }
  BRANCH=${VERSION%.*}
  BUILD=${VERSION##*.}
  if [ $BRANCH == 2.0 ] && (( "$BUILD" >= "22" )); then
    MSG=">= 2.0.22"
    RC=$NAGIOS_OK
  elif [ $BRANCH == 2.1 ] && (( "$BUILD" >= "14" )); then
    MSG=">= 2.1.14"
    RC=$NAGIOS_OK
  elif (echo "${HASH2_0}  /etc/auto.cvmfs" | md5sum --check --status) || 
       (echo "${HASH2_1}  /etc/auto.cvmfs" | md5sum --check --status); then
    MSG="with applied hotfix"
    RC=$NAGIOS_OK
  else
    MSG="without hotfix"
  fi
  MSG="cvmfs version $VERSION found $MSG at $HOSTNAME"
  MSG="$MSG\\nMD5 hash $(md5sum /etc/auto.cvmfs)"
fi

case $RC in
  $NAGIOS_OK      ) echo -e "OK: $MSG";;
  $NAGIOS_WARNING ) echo -e "WARNING: $MSG";;
  $NAGIOS_ERROR   ) echo -e "ERROR: $MSG";;
  $NAGIOS_UNKNOWN ) echo -e "UNKNOWN: $MSG";;
esac

echo "probe version ${PROBE_VERSION}"
exit $RC

