#!/bin/bash
cur_path=`dirname $0`

result=`${cur_path}/pakiti-client -a ${cur_path}/pakiti_cas 2>&1`
exit_status=$?

if [ ${exit_status} == 0 ]; then
  echo "OK: Pakiti reported correctly to all the configured servers."
else
  if [ ${exit_status} == 1 ]; then
    echo "WARNING: Pakiti didn't report to all configured servers."
  else
    echo "ERROR: There was an error on pakiti reporting."
  fi
fi
echo ${result}|sed -e "s# ERROR#\nERROR#g" -e "s# WARNING#\nWARNING#g"
exit ${exit_status}
