#!/bin/bash

NAGIOS_OK=0
NAGIOS_WARNING=1
NAGIOS_ERROR=2
NAGIOS_UNKNOWN=3

# Trying to execute qmgr
type qmgr 2>/dev/null
[ $? -ne 0 ] && echo "qmgr is not available. Assuming that other LRMS is used." && exit $NAGIOS_OK

QMGR_RESULT=$(qmgr -c "pr se" 2>&1)
RES=$?
if [ ${RES} != "0" ]
then
   echo "qmgr execution failed"
   exit $NAGIOS_UNKNOWN
fi

bad_option="set server disable_server_id_check = True"

has_bad_option=`echo $QMGR_RESULT | grep $bad_option 2>&1`
if [ $? == "0" ]
then
  echo "The server appears to have disable_server_id_check = True"
  exit $NAGIOS_CRITICAL
else 
  echo "The server doesn't appear to have disable_server_id_check = True"
  exit $NAGIOS_OK
fi
